### ISSUE TITLE
Add support for S3 regions

### ISSUE THREAD

**Issue by ghost** [SocialFlowDev/SocialFlow-S3#8]
S3 supports distinct physical locations as the storage spot for data. I thought it was as simple as setting a specific URL to issue requests against but its not. Details are at http://docs.aws.amazon.com/AmazonS3/latest/dev/LocationSelection.html

**Comment by leonerd** [comment]
Mmm, reading the link above that seems to apply only at the bucket level, set when you create the bucket. As sfs3 doesn't create buckets, only uses keys within them, I don't see what sfs3 can do with region support.

**Comment by ghost** [comment]
Reading through it again its not quite as I expected but there is a difference in the behavior from the default method and specifying a region as well as specifying a bucket as part of the hostname or as part of the request path. This is a low priority enhancement but supporting this would be a part of handling S3 completely.

**Comment by leonerd** [comment]
On further discussion with triddle it appears we mostly already do support these regions by virtue of using the bucket name in part of the hostname, to perform a bucket-specific IP address lookup.

One thing we may be able to do however, is cache the results of any HTTP redirects that occur, which would reduce the number of roundtrips.

**Comment by leonerd** [comment]
Hmm.. recent testing suggests that there aren't any HTTP-level redirects going on:

  $ IO_ASYNC_DEBUG=1 perl -Mblib bin/sfs3 ls
  [Na:HTTP::Connection{a-bucket-and-some-jifjeakfjaljfeioahj.s3.amazonaws.com:443}<-Na:HTTP<-Na:Webservice::S3<-SocialFlow::S3] CONNECT a-bucket-and-some-jifjeakfjaljfeioahj.s3.amazonaws.com:443
  [Ia:Stream{r=5}<-Ia:Channel<-Ia:Function::Worker<-Ia:Resolver] EVENT on_read
  [Ia:Handle{rw=3}] EVENT on_read_ready
  [Ia:Handle{rw=3}] EVENT on_read_ready
  [Ia:Handle{rw=3}] EVENT on_read_ready
  [Ia:Handle{rw=3}] EVENT on_read_ready
  [Na:HTTP::Connection{a-bucket-and-some-jifjeakfjaljfeioahj.s3.amazonaws.com:443}<-Na:HTTP<-Na:Webservice::S3<-SocialFlow::S3] CONNECTED
  [Na:HTTP::Connection{a-bucket-and-some-jifjeakfjaljfeioahj.s3.amazonaws.com:443}<-Na:HTTP<-Na:Webservice::S3<-SocialFlow::S3] READY non-pipelined
  [Na:HTTP::Connection{a-bucket-and-some-jifjeakfjaljfeioahj.s3.amazonaws.com:443}<-Na:HTTP<-Na:Webservice::S3<-SocialFlow::S3] REQUEST GET https://a-bucket-and-some-jifjeakfjaljfeioahj.s3.amazonaws.com/?delimiter=%2F&max-keys=1000&prefix=pevans-test%2Fdata%2F
  [Na:HTTP::Connection{a-bucket-and-some-jifjeakfjaljfeioahj.s3.amazonaws.com:443}<-Na:HTTP<-Na:Webservice::S3<-SocialFlow::S3] HEADER 200 OK
  [Na:HTTP::Connection{a-bucket-and-some-jifjeakfjaljfeioahj.s3.amazonaws.com:443}<-Na:HTTP<-Na:Webservice::S3<-SocialFlow::S3] BODY chunks
  [Na:HTTP::Connection{a-bucket-and-some-jifjeakfjaljfeioahj.s3.amazonaws.com:443}<-Na:HTTP<-Na:Webservice::S3<-SocialFlow::S3] BODY done
  [Na:HTTP::Connection{a-bucket-and-some-jifjeakfjaljfeioahj.s3.amazonaws.com:443}<-Na:HTTP<-Na:Webservice::S3<-SocialFlow::S3] DONE remaining in-flight=0
  [Na:HTTP::Connection{a-bucket-and-some-jifjeakfjaljfeioahj.s3.amazonaws.com:443}<-Na:HTTP<-Na:Webservice::S3<-SocialFlow::S3] READY pipelined

Receives a 200 OK rather than a 3xx redirection. Suggests there isn't much left we can do here.

**Comment by leonerd** [comment]
This has been determined not to matter any more; can close this.
