### ISSUE TITLE
Support parallel upload for single files and from stdin

### ISSUE THREAD

**Issue by ghost** [SocialFlowDev/SocialFlow-S3#9]
sfs3 should support parallel uploads when uploading only a single file or when reading input from stdin.

**Comment by leonerd** [comment]
Have added parallel concurrency to the underlying NaWebservice:S3 now, so hopefully all that remains is to enable it from sfs3 and give it some testing.

The unencrypted regular file case will need a bit of extra work to ensure that the concurrent upload streams sysseek() the filehandle correctly after each read, as they'll now be concurrently trying to read different parts of the file.

**Comment by leonerd** [comment]
Actually this is a bit messier than I thought, because of the incremental MD5 checksum buffer. concurrent uploads from pipes should be fine, but concurrent uploads from regular files try to optimise with seek+read, and will append the buffer all out-of-order.

I think what's needed is an atomic "read me a 100MB buffer from the file and let me know when it's ready" IO::Async primitive, so that can be used to generate parts in the right order.
